### ISSUE TITLE
Global search unexpected result

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-web-client#51]
When I search for Bisphenol A in the global search, typing Bisph brings up a list that contains Bisphenol A. When I select Bisphenol A from the list, then search, I get no result, however, Bisphenol A is clearly in the DB since it is in the list.  If I change the search to bisphenol without the ' A', the search returns the compound.  It is not clear why the full name selected from the list does not work.
Search done when connected with Chrome.

**Comment by Luke-Malchow-Bergenthal** [comment]
Ah, this is frustrating. I believe it is because the search backend, whoosh, is delimiting on white space and then treating each separated word as an object called an Ngram (basically a bunch of different segments of a word). Problem is, whoosh does not convert words with one or two characters into Ngrams, so 'A' becomes an invalid Ngram and I suppose things simply stop.

I will have to look into this.

**Comment by Luke-Malchow-Bergenthal** [comment]
I have modified the whoosh settings with a somewhat ugly extension as of https://github.com/UPDDI/mps-database-server/commit/3825b3494dc1e470fcf53c2b65e05bd5342d93f0. Please try searching on Stage to confirm stability.

**Comment by Luke-Malchow-Bergenthal** [comment]
Should be resolved as of https://github.com/UPDDI/mps-web-client/commit/c93c5a4d4754f63c15a851e4eb1acef99356991b. Closing.
